export const DATABASES_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const WORKSPACES_ID = process.env.NEXT_PUBLIC_APPWRITE_WORKSPACES_ID!;
export const MEMBER_ID = process.env.NEXT_PUBLIC_APPWRITE_MEMBER_ID!;
export const IMAGES_ID = process.env.NEXT_PUBLIC_APPWRITE_IMAGES_BUCKET_ID!;